#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -rf build dist

# we want all these files to exist in the actual package
_CI/scripts/copy_version_file

python setup.py sdist bdist_egg

_CI/scripts/remove_version_file
