#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

pip3 install -r requirements/build.txt

rm -rf build dist

# we want all these files to exist in the actual package
_CI/scripts/copy_version_file

python3 -m build --sdist --wheel

_CI/scripts/remove_version_file
