#!/bin/bash --login
cd $(dirname $0)/../..

. ./_CI/scripts/bootstrap

pip3 install -r requirements/testing.txt

rm -rf test-output
mkdir -p test-output/coverage
touch test-output/coverage/index.html
tox
exit_code=$?

if [[ -z "${CI}" ]]; then
    # if NOT in a CI env then do the following
    open test-output/coverage/index.html 2> /dev/null|| xdg-open test-output/coverage/index.html &
    sleep 1
    open test-output/nosetests.html 2> /dev/null|| xdg-open test-output/nosetests.html &
    exit $exit_code
fi
