#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -rf build dist

if test -n "${TRAVIS}"
then
    echo "Creating pypirc file"
    cat << EOF > ~/.pypirc
[distutils]
index-servers = pypi

[pypi]
username: ${PYPI_USER}
password: ${PYPI_PASSWORD}
EOF
fi
# we want all these files to exist in the actual package
_CI/scripts/copy_version_file

python setup.py sdist upload

test -n "${TRAVIS}" && rm -vf ~/.pypirc

_CI/scripts/remove_version_file
