#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -rf build dist

if test -n "${TRAVIS}"
then
    if test -z "${TRAVIS_TAG}"
    then
        echo "Not a tagged build, not uploading"
        exit 0
    fi
    echo "Creating pypirc file"
    cat << EOF > ~/.pypirc
[distutils]
index-servers = pypi

[pypi]
username: ${PYPI_USER}
password: ${PYPI_PASSWORD}
EOF
fi
# we want all these files to exist in the actual package
_CI/scripts/copy_version_file

python setup.py -v sdist upload --show-response -r pypi

test -n "${TRAVIS}" && rm -vf ~/.pypirc

_CI/scripts/remove_version_file
