#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -rf build dist

test -z "${TRAVIS}" && cat << EOF > ~/.pypirc
[distutils]
index-servers =
    pypi

[pypi]
username: ${PYPI_USER}
password: ${PYPI_PASSWORD}
EOF
# we want all these files to exist in the actual package
_CI/scripts/copy_version_file

python setup.py sdist bdist_egg upload

test -z "${TRAVIS}" && rm -f ~/.pypirc

_CI/scripts/remove_version_file
