name: build and publish

on:
  push:
      tags:
          - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install support tools
        run: pip install virtualenv virtualenvwrapper

      - name: lint
        run: ./_CI/scripts/lint

      - name: test
        run: ./_CI/scripts/test

      - name: build
        run: ./_CI/scripts/build

      - name: upload
        env:
          PYPI: ${{ secrets.PYPI }}
        run: ./_CI/scripts/upload

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: hsmade/certbot-transip:latest
